<?php

namespace Tests;


use Orchestra\Testbench\TestCase as BaseTestCase;
use OfflineAgency\FattureInCloud\FattureInCloudServiceProvider;

abstract class TestCase extends BaseTestCase
{
  use CreatesApplication;

  protected function getPackageProviders($app)
  {
    return [
      FattureInCloudServiceProvider::class
    ];
  }

  public function setUp(): void
  {
    parent::setUp();
  }

  protected function getEnvironmentSetUp($app)
  {
    $app['config']->set('fatture-in-cloud.api_uid', 'fake_uid');
    $app['config']->set('fatture-in-cloud.api_key', 'fake_api_key');
  }

  /**
   * @param string $string
   * @return string
   */
  protected function getHttpResponse(string $string): string
  {
    return json_encode([
      'lista_paesi' =>
        [
          0 => 'Afghanistan',
          1 => 'Albania',
          2 => 'Algeria',
          3 => 'Andorra',
          4 => 'Angola',
          5 => 'Anguilla',
          6 => 'Antartide',
          7 => 'Antigua e Barbuda',
          8 => 'Antille Olandesi',
          9 => 'Arabia Saudita',
          10 => 'Argentina',
          11 => 'Armenia',
          12 => 'Aruba',
          13 => 'Australia',
          14 => 'Austria',
          15 => 'Azerbaigian',
          16 => 'Bahamas',
          17 => 'Bahrain',
          18 => 'Bangladesh',
          19 => 'Barbados',
          20 => 'Belgio',
          21 => 'Belize',
          22 => 'Benin',
          23 => 'Bermuda',
          24 => 'Bhutan',
          25 => 'Bielorussia',
          26 => 'Bolivia',
          27 => 'Bosnia ed Erzegovina',
          28 => 'Botswana',
          29 => 'Brasile',
          30 => 'Brunei',
          31 => 'Bulgaria',
          32 => 'Burkina Faso',
          33 => 'Burundi',
          34 => 'Cambogia',
          35 => 'Camerun',
          36 => 'Canada',
          37 => 'Capo Verde',
          38 => 'Ciad',
          39 => 'Cile',
          40 => 'Cina',
          41 => 'Cipro',
          42 => 'Città del Vaticano',
          43 => 'Colombia',
          44 => 'Comore',
          45 => 'Corea del Nord',
          46 => 'Corea del Sud',
          47 => 'Costa Rica',
          48 => 'Costa d\'Avorio',
          49 => 'Croazia',
          50 => 'Cuba',
          51 => 'Danimarca',
          52 => 'Dominica',
          53 => 'Ecuador',
          54 => 'Egitto',
          55 => 'El Salvador',
          56 => 'Emirati Arabi Uniti',
          57 => 'Eritrea',
          58 => 'Estonia',
          59 => 'Etiopia',
          60 => 'Fiji',
          61 => 'Filippine',
          62 => 'Finlandia',
          63 => 'Francia',
          64 => 'Gabon',
          65 => 'Gambia',
          66 => 'Georgia',
          67 => 'Georgia del Sud e isole Sandwich',
          68 => 'Germania',
          69 => 'Ghana',
          70 => 'Giamaica',
          71 => 'Giappone',
          72 => 'Gibilterra',
          73 => 'Gibuti',
          74 => 'Giordania',
          75 => 'Grecia',
          76 => 'Grenada',
          77 => 'Groenlandia',
          78 => 'Guadalupa',
          79 => 'Guam',
          80 => 'Guatemala',
          81 => 'Guinea',
          82 => 'Guinea Equatoriale',
          83 => 'Guinea-Bissau',
          84 => 'Guyana',
          85 => 'Guyana Francese',
          86 => 'Haiti',
          87 => 'Heard Island e McDonald Islands',
          88 => 'Honduras',
          89 => 'Hong Kong',
          90 => 'India',
          91 => 'Indonesia',
          92 => 'Iran',
          93 => 'Iraq',
          94 => 'Irlanda',
          95 => 'Islanda',
          96 => 'Isola Bouvet',
          97 => 'Isola Christmas',
          98 => 'Isola di Man',
          99 => 'Isola Norfolk',
          100 => 'Isole Canarie (Spagna)',
          101 => 'Isole Cayman',
          102 => 'Isole Cocos e Keeling',
          103 => 'Isole Cook',
          104 => 'Isole Falkland',
          105 => 'Isole Fær Øer',
          106 => 'Isole Marianne Settentrionali',
          107 => 'Isole Marshall',
          108 => 'Isole Minori Esterne degli USA',
          109 => 'Isole Pitcairn',
          110 => 'Isole Salomone',
          111 => 'Isole Vergini Americane',
          112 => 'Isole Vergini Britanniche',
          113 => 'Isole Åland',
          114 => 'Israele',
          115 => 'Italia',
          116 => 'Jersey - Channel Islands',
          117 => 'Kazakistan',
          118 => 'Kenia',
          119 => 'Kirghizistan',
          120 => 'Kiribati',
          121 => 'Kosovo',
          122 => 'Kuwait',
          123 => 'Laos',
          124 => 'Lesotho',
          125 => 'Lettonia',
          126 => 'Libano',
          127 => 'Liberia',
          128 => 'Libia',
          129 => 'Liechtenstein',
          130 => 'Lituania',
          131 => 'Lussemburgo',
          132 => 'Macao',
          133 => 'Macedonia',
          134 => 'Macedonia del Nord',
          135 => 'Madagascar',
          136 => 'Malawi',
          137 => 'Malaysia',
          138 => 'Maldive',
          139 => 'Mali',
          140 => 'Malta',
          141 => 'Marocco',
          142 => 'Martinica',
          143 => 'Mauritania',
          144 => 'Mauritius',
          145 => 'Mayotte',
          146 => 'Messico',
          147 => 'Micronesia',
          148 => 'Moldavia',
          149 => 'Monaco',
          150 => 'Mongolia',
          151 => 'Montenegro',
          152 => 'Montserrat',
          153 => 'Mozambico',
          154 => 'Myanmar',
          155 => 'Namibia',
          156 => 'Nauru',
          157 => 'Nepal',
          158 => 'Nicaragua',
          159 => 'Niger',
          160 => 'Nigeria',
          161 => 'Niue',
          162 => 'Norvegia',
          163 => 'Nuova Caledonia',
          164 => 'Nuova Zelanda',
          165 => 'Oman',
          166 => 'Paesi Bassi',
          167 => 'Pakistan',
          168 => 'Palau',
          169 => 'Panama',
          170 => 'Papua Nuova Guinea',
          171 => 'Paraguay',
          172 => 'Perù',
          173 => 'Polinesia Francese',
          174 => 'Polonia',
          175 => 'Porto Rico',
          176 => 'Portogallo',
          177 => 'Qatar',
          178 => 'Regno Unito',
          179 => 'Repubblica Ceca',
          180 => 'Repubblica Centrafricana',
          181 => 'Repubblica Democratica del Congo',
          182 => 'Repubblica Dominicana',
          183 => 'Repubblica del Congo',
          184 => 'Riunione',
          185 => 'Romania',
          186 => 'Ruanda',
          187 => 'Russia',
          188 => 'Sahara Occidentale',
          189 => 'Saint Barthelemy',
          190 => 'Saint Kitts e Nevis',
          191 => 'Saint Pierre e Miquelon',
          192 => 'Saint Vincent e Grenadine',
          193 => 'Samoa',
          194 => 'Samoa Americane',
          195 => 'San Marino',
          196 => 'Sant\'Elena',
          197 => 'Santa Lucia',
          198 => 'Senegal',
          199 => 'Serbia',
          200 => 'Seychelles',
          201 => 'Sierra Leone',
          202 => 'Singapore',
          203 => 'Siria',
          204 => 'Slovacchia',
          205 => 'Slovenia',
          206 => 'Somalia',
          207 => 'Spagna',
          208 => 'Sri Lanka',
          209 => 'Stato di Palestina',
          210 => 'Stati Uniti',
          211 => 'Sudafrica',
          212 => 'Sud Sudan',
          213 => 'Sudan',
          214 => 'Suriname',
          215 => 'Svalbard e Jan Mayen',
          216 => 'Svezia',
          217 => 'Svizzera',
          218 => 'Swaziland',
          219 => 'São Tomé e Príncipe',
          220 => 'Tagikistan',
          221 => 'Taiwan',
          222 => 'Tanzania',
          223 => 'Terre australi e ant. francesi',
          224 => 'Territori Palestinesi',
          225 => 'Terr. Britannico dell\'Oc. Ind.',
          226 => 'Thailandia',
          227 => 'Timor Est',
          228 => 'Togo',
          229 => 'Tokelau',
          230 => 'Tonga',
          231 => 'Trinidad e Tobago',
          232 => 'Tunisia',
          233 => 'Turchia',
          234 => 'Turkmenistan',
          235 => 'Turks e Caicos',
          236 => 'Tuvalu',
          237 => 'Ucraina',
          238 => 'Uganda',
          239 => 'Ungheria',
          240 => 'Uruguay',
          241 => 'Uzbekistan',
          242 => 'Vanuatu',
          243 => 'Venezuela',
          244 => 'Vietnam',
          245 => 'Wallis e Futuna',
          246 => 'Yemen',
          247 => 'Zambia',
          248 => 'Zimbabwe',
        ],
      'success' => true,
    ]);
  }
}
